### ISSUE TITLE
setuptools must be installed to install from a source distribution

### ISSUE THREAD

**Issue by tylerecouture** [Chive/django-multiupload#12]
Any idea why I'm getting this error why I try to install with pip?

$ pip install django-multiupload
Collecting django-multiupload
  Downloading django-multiupload-0.5.tar.gz
setuptools must be installed to install from a source distribution

**Comment by Badredapple** [comment]
I also getting this error ,when I try to install with pip
~# pip install --pre github3.py
then I get this: 
Downloading/unpacking uritemplate.py>=0.2.0 (from github3.py)
  Downloading uritemplate.py-0.3.0.tar.gz
Cleaning up...
setuptools must be installed to install from a source distribution
Storing debug log for failure in /root/.pip/pip.log

Maybe I need to uninstall my setuptools and update it into 
version 20.1?

**Comment by Badredapple** [comment]
OK , I solve this question  by use " pip install setuptools --upgrade"
That's work well ,Help this can help you
