### ISSUE TITLE
pep8 style

### ISSUE THREAD

**Issue by sobolevn** [Chive/django-multiupload#17]
Hey! Thanks for your project.

I am using it with no issues, but today I have looked inside. This project needs some good style fixing. 
I can send you a PR, if that's okay.

May be you should also consider using `pylint`? I can also add this check to the `.travis.yml`.

**Comment by Chive** [comment]
Hey @sobolevn 

Sure, PR's are always welcome - feel free to add pylint too!

Best,
Kim

**Comment by Chive** [comment]
closed in #18
