### ISSUE TITLE
pip django-multiupload not up to date

### ISSUE THREAD

**Issue by shakle17** [Chive/django-multiupload#21]
Installing django-multiupload with `pip install django-multiupload` allows using only `MultiFileField` , but not `MultiMediaField` & `MultiImageField`. You should update the package on pip

**Comment by Chive** [comment]
Thanks for the notification @shakle17. I've released a new version [`0.5.2`](https://github.com/Chive/django-multiupload/releases/tag/0.5.2) on [PyPi](https://pypi.python.org/pypi/django-multiupload)
