### ISSUE TITLE
IntegrityError when implement multiupload

### ISSUE THREAD

**Issue by valdivieso01** [Chive/django-multiupload#30]
Hi!

When tray to upload files in my project show this error:
![image](https://user-images.githubusercontent.com/8400669/47472752-310a2b00-d7e6-11e8-9f4b-15b7915f06d4.png)

the code is:
![image](https://user-images.githubusercontent.com/8400669/47472838-7c243e00-d7e6-11e8-95ed-ac267bbb947e.png)

![image](https://user-images.githubusercontent.com/8400669/47472857-8c3c1d80-d7e6-11e8-9e47-243c573b3848.png)

![image](https://user-images.githubusercontent.com/8400669/47472876-99f1a300-d7e6-11e8-8fc8-59d5441a673f.png)

**Comment by Chive** [comment]
Hi @valdivieso01 

That's an issue in your code, the line you highlighted should include the `set` argument

```
Guide.objects.create(file=each, set=something)
```

However closing this because it's not an issue with django-multiupload.

Thanks
