### ISSUE TITLE
render() got an unexpected keyword argument 'renderer' django 2.2

### ISSUE THREAD

**Issue by godfather68** [Chive/django-multiupload#31]
I am having this problem that I can't work out for days now. I am trying to upload multiple image and I came across django-multiupload but anytime I try to parse the form( which contains a simple Image attribute of type MultiImageField() ) into the view function I get this error. 

Does someone know why ?

**Comment by leliel12** [comment]
im also have the same problem

**Comment by godfather68** [comment]
Well , according to the docs [See here](https://docs.djangoproject.com/en/2.1/releases/2.1/#features-removed-in-2-1), some features have been removed from 2.1 the one we're looking at is the following:

> Support for Widget.render() methods without the renderer argument is removed.

and I believe this repo is not maintained for django >= 2.1 features .

So you  might want to locate and alter the file **fields.py** . It can be found under 

> _your-python-installation/site-packages/multiupload/fields.py_

The **render()** method inside that file probably looks like the following : 

```
def render(self, name, value, attrs=None):
        if self.multiple:
            attrs['multiple'] = 'multiple'
```

Fix it so it looks like this instead

```
def render(self, name, value, attrs=None, renderer=None):
        if self.multiple:
            attrs['multiple'] = 'multiple'
```
It should fix it .

**Comment by hangtwenty** [comment]
Latest `master` has the fix (at time of writing: ba52e161a68ce19062c3655e89544c2d377990a0). Argument for pip: `git+git://github.com/Chive/django-multiupload.git@ba52e161a68ce19062c3655e89544c2d377990a0#egg=multiupload`

**Comment by cddumanov** [comment]
upgrade pip to this commit please

**Comment by pedrofaria09** [comment]
Hello, I have this same error. Hope someone can help me, please.
Some info about my project:
Django Version: | 3.1.7
Python Version: | 3.7.11

My models.py:
class Intervention(models.Model):
     tower = models.ForeignKey('Tower', on_delete=models.DO_NOTHING)
     .... //got many other attributes

class InterventionData(models.Model):
    interv = models.ForeignKey(Intervention, on_delete=models.CASCADE)
    files = models.FileField(upload_to="attachments")

My forms.py:
class InterventionForm(ModelForm):
    files = MultiFileField(min_num=1, max_num=3, max_file_size=1024*1024*5)
    class Meta:
        model = Intervention
        fields = ('tower',...) //got many other attributes
    def __init__(self, *args, **kwargs):
        super(InterventionForm, self).__init__(*args, **kwargs)
        self.fields['tower'].label = "Tower"
        .... //got many other attributes

    def save(self, commit=True):
        instance = super(InterventionForm, self).save(commit)
        for each in self.cleaned_data['files']:
            InterventionData.objects.create(files=each, interv=instance)
        return instance

My views.py:
def view_intervention(request, interv_id):
    try:
        interv = Intervention.objects.get(pk=interv_id)
    except Intervention.DoesNotExist:
        return HttpResponseRedirect(reverse("list_interventions"))

    if request.method == 'GET':
        form = InterventionForm(instance=interv)
        ....
    elif request.method == 'POST':
        form = InterventionForm(request.POST, request.FILES, instance=interv)
        if form.is_valid():
            interv = form.save(commit=False)
            ...
            form.save()
    return render(request, 'view_intervention.html', {'form': form, 'interv_id': interv_id, 'interv': interv})

![Uploading Screenshot at Oct 05 12-32-29.png…]()

**Comment by Chive** [comment]
@pedrofaria09 This was resolved in https://github.com/Chive/django-multiupload/commit/4937d6993afed3ef9b97829f9173e30cc671d66e and released in https://github.com/Chive/django-multiupload/releases/tag/0.6.1
