### ISSUE TITLE
Python3 compatibility

### ISSUE THREAD

**Issue by C4ptainCrunch** [Chive/django-multiupload#8]
Hi

When running [`caniusepython3`](https://github.com/brettcannon/caniusepython3) on my project, `django-multiupload` is the only requirement that is flagged as Python3 incompatible.

I tried `pip install django-multiupload` in a fresh python3 virtualenv and it didn't fail. Thus is django-multiupload python3 compatible and the classifier in `setup.py` is just missing or is there an other reason?

PS : Thanks for this great piece of software :)

**Comment by Chive** [comment]
Thanks @C4ptainCrunch !

**Comment by C4ptainCrunch** [comment]
Wow, that was fast, thanks ! :)
