### ISSUE TITLE
Can it be used instead of ImageField?

### ISSUE THREAD

**Issue by qasimalbaqali** [Chive/django-multiupload#9]
This works for images as well doesn't it?

**Comment by Chive** [comment]
Sure! This works for media types (images, videos, sound files etc) just as well as for plain file types! Also allows you to mix them during one upload (e.g. attach an image and a pdf document at the same time).

**Comment by tnakasaki** [comment]
If you use MultiFieldField on your form for a ImageField model field, uploaded files will not be validated to ensure that they are image files.
MultiFileField class definition in forms.py needs to inherit from forms.ImageField (instead of forms.FileField) to keep this validation functionality.

**Comment by qasimalbaqali** [comment]
@tnakasaki is that already done, or do I need to do that my self? Excuse my 'noobness'

**Comment by tnakasaki** [comment]
@qasimalbaqali
You can just definite your own new image form field like this:

class MultiImageField(MultiFileField, forms.ImageField):
    pass

Then you'll have a multiple image upload field (thanks to MultiFileFIeld) that inherits the validation properties of forms.ImageField

I think so anyway...

**Comment by tnakasaki** [comment]
@qasimalbaqali I think you need to bind the data to your form object this way
https://docs.djangoproject.com/en/1.8/ref/forms/api/#binding-uploaded-files
